package com.resolvix.ohm.module.endpoint.api

import com.resolvix.ohm.api.AlertStatus

/**
  * Defines a generic form of [[com.resolvix.ohm.module.api.Result]] that is
  * generated by modules that implement the [[com.resolvix.ohm.module.endpoint.api.Endpoint]]
  * trait.
  */
trait EndpointResult
  extends com.resolvix.ohm.module.api.Result
{
  def getAlertStatuses: Iterable[AlertStatus]
}
